/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.aas.apps.mvc.view;

import id.aas.apps.mvc.controller.laundryKiloanController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aas Suhendar
 */
public class UIDlaundryKiloan extends javax.swing.JFrame {

    private laundryKiloanController lkController;
    private final DefaultTableModel tableModel;

    /**
     * Creates new form UIDlaundryKiloan
     */
    public UIDlaundryKiloan() {
        initComponents();
        lkController = new laundryKiloanController();
        tableModel = new DefaultTableModel();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jTable.setModel(tableModel);
        this.setSize(450, 550);
        this.setLocationRelativeTo(null);
        RunApps();
    }

    public laundryKiloanController getLkController() {
        return lkController;
    }

    public void setLkController(laundryKiloanController lkController) {
        this.lkController = lkController;
    }

    public void setTableHeader() {
        Object[] header = lkController.getHeaderTable();
        for (Object header1 : header) {
            tableModel.addColumn(header1);
        }
    }

    public void setIsiDataLKiloan() {
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();

        ArrayList<Object[]> data = null;
        try {
            data = lkController.getAllDataLKiloan();
            for (int i = 0; i < data.size(); i++) {
                tableModel.addRow(data.get(i));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public void RunApps() {
        try {
            this.setTableHeader();
            this.setIsiDataLKiloan();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void reset() {
        jtxtKode.setText("");
        jtxtHarga.setText("");
        jComboStatus.setSelectedIndex(0);
        jtxtKode.requestFocus();
                
    }

    public void isiField() {
        int row = jTable.getSelectedRow();
        jtxtKode.setText(jTable.getValueAt(row, 0).toString());
        jtxtHarga.setText(jTable.getValueAt(row, 1).toString());
        jComboStatus.setSelectedItem(jTable.getValueAt(row, 2).toString());
        jbtnSimpanEdit.setText("Edit");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new id.aas.apps.mvc.usuDesign.Panel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelAlpha1 = new id.aas.apps.mvc.usuDesign.PanelAlpha();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboStatus = new javax.swing.JComboBox();
        jtxtKode = new id.aas.apps.mvc.usuDesign.TextBox();
        jtxtHarga = new id.aas.apps.mvc.usuDesign.TextBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jbtnSimpanEdit = new id.aas.apps.mvc.usuDesign.Button();
        jbtnHapus = new id.aas.apps.mvc.usuDesign.Button();
        jbtnMenuUtama2 = new id.aas.apps.mvc.usuDesign.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel6.setText("Aplikasi Pencatatan Laundry");
        panel1.add(jLabel6);
        jLabel6.setBounds(90, 20, 221, 22);

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel7.setText("Roemah Cemerlang Laundry");
        panel1.add(jLabel7);
        jLabel7.setBounds(90, 40, 293, 29);
        panel1.add(jLabel8);
        jLabel8.setBounds(40, 60, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/laundry1111.png"))); // NOI18N
        panel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 70, 80);

        panelAlpha1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Form Harga Kiloan Laundry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        panelAlpha1.setForeground(new java.awt.Color(255, 255, 255));
        panelAlpha1.setLayout(null);

        jLabel2.setText("Kode Kiloan");
        panelAlpha1.add(jLabel2);
        jLabel2.setBounds(30, 30, 80, 14);

        jLabel3.setText("Harga per Kilo");
        panelAlpha1.add(jLabel3);
        jLabel3.setBounds(30, 70, 80, 14);

        jLabel4.setText("Status");
        panelAlpha1.add(jLabel4);
        jLabel4.setBounds(30, 100, 70, 14);

        jComboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Aktif", "Non Aktif" }));
        panelAlpha1.add(jComboStatus);
        jComboStatus.setBounds(110, 100, 69, 20);
        panelAlpha1.add(jtxtKode);
        jtxtKode.setBounds(110, 24, 250, 30);
        panelAlpha1.add(jtxtHarga);
        jtxtHarga.setBounds(110, 60, 250, 30);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        panelAlpha1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 360, 160);

        jbtnSimpanEdit.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSimpanEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/save_all.png"))); // NOI18N
        jbtnSimpanEdit.setText("Simpan");
        jbtnSimpanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSimpanEditActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnSimpanEdit);
        jbtnSimpanEdit.setBounds(120, 140, 120, 40);

        jbtnHapus.setForeground(new java.awt.Color(0, 0, 0));
        jbtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/gnome_edit_delete.png"))); // NOI18N
        jbtnHapus.setText("Hapus");
        jbtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHapusActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnHapus);
        jbtnHapus.setBounds(250, 140, 120, 40);

        panel1.add(panelAlpha1);
        panelAlpha1.setBounds(20, 120, 400, 360);

        jbtnMenuUtama2.setForeground(new java.awt.Color(0, 0, 0));
        jbtnMenuUtama2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/home.png"))); // NOI18N
        jbtnMenuUtama2.setText("Menu Utama");
        jbtnMenuUtama2.setActionCommand("jbtnMenuUtama");
        jbtnMenuUtama2.setFocusPainted(false);
        jbtnMenuUtama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenuUtama2ActionPerformed(evt);
            }
        });
        panel1.add(jbtnMenuUtama2);
        jbtnMenuUtama2.setBounds(300, 80, 130, 30);

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            isiField();
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jbtnSimpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSimpanEditActionPerformed
        // TODO add your handling code here:
        try {
            boolean validasi = false;
            String kode = jtxtKode.getText();
            String harga = jtxtHarga.getText();
            String status = jComboStatus.getSelectedItem().toString();
            String btnStatus = jbtnSimpanEdit.getText();
            if (kode.isEmpty() || harga.isEmpty() || status.equals("-Pilih-")) {
                JOptionPane.showMessageDialog(null, "Terdapat Field Kosong, harap mengisi semua field", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (btnStatus.equalsIgnoreCase("Simpan")) {
                    validasi = lkController.olahDataLKiloan(btnStatus, kode, harga, status);
                } else if (btnStatus.equalsIgnoreCase("Edit")) {
                    validasi = lkController.olahDataLKiloan(btnStatus, kode, harga, status);
                }

                if (validasi == true) {
                    setIsiDataLKiloan();
                    if (btnStatus.equalsIgnoreCase("Simpan")) {
                        JOptionPane.showMessageDialog(null, "Data Harga Kiloan Laundry Berhasil Disimpan", "Simpan Harga Kiloan Laundry", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Harga Kiloan Laundry Berhasil Diedit", "Simpan Harga Kiloan Laundry", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    if (btnStatus.equalsIgnoreCase("Simpan")) {
                        JOptionPane.showMessageDialog(null, "Data Harga Kiloan Laundry Gagal Disimpan", "Simpan Harga Kiloan Laundry", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Harga Kiloan Laundry Gagal Diedit", "Simpan Harga Kiloan Laundry", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                reset();
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnSimpanEditActionPerformed

    private void jbtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHapusActionPerformed
        // TODO add your handling code here:
        try {
            int row = jTable.getSelectedRow();
            String kode = jTable.getValueAt(row, 0).toString();
            boolean validasi = lkController.hapusDataLKiloan(kode);
            if (validasi == true) {
                setIsiDataLKiloan();
                JOptionPane.showMessageDialog(null, "Data Harga Kiloan Laundry Berhasil Dihapus", "Hapus Data Harga Kiloan Laundry", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Data Harga Kiloan Laundry Gagal Dihapus", "Hapus Data harga Kiloan Laundry", JOptionPane.INFORMATION_MESSAGE);
            }
            reset();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnHapusActionPerformed

    private void jbtnMenuUtama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenuUtama2ActionPerformed
        // TODO add your handling code here:
        new UIDmenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnMenuUtama2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDlaundryKiloan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDlaundryKiloan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDlaundryKiloan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDlaundryKiloan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDlaundryKiloan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private id.aas.apps.mvc.usuDesign.Button jbtnHapus;
    private id.aas.apps.mvc.usuDesign.Button jbtnMenuUtama2;
    private id.aas.apps.mvc.usuDesign.Button jbtnSimpanEdit;
    private id.aas.apps.mvc.usuDesign.TextBox jtxtHarga;
    private id.aas.apps.mvc.usuDesign.TextBox jtxtKode;
    private id.aas.apps.mvc.usuDesign.Panel panel1;
    private id.aas.apps.mvc.usuDesign.PanelAlpha panelAlpha1;
    // End of variables declaration//GEN-END:variables
}
