/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.aas.apps.mvc.view;

import id.aas.apps.mvc.controller.adminController;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aas Suhendar
 */
public class UIDLogin extends javax.swing.JFrame {

    private adminController adminCon;

    /**
     * Creates new form UIDLogin
     */
    public UIDLogin() {
        initComponents();
        adminCon = new adminController();
        setSize(530, 330);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public void reset() {
        jtxtUsername.setText("");
        jtxtPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new id.aas.apps.mvc.usuDesign.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtUsername = new id.aas.apps.mvc.usuDesign.TextBox();
        jbtnLogin = new id.aas.apps.mvc.usuDesign.Button();
        jtxtPassword = new id.aas.apps.mvc.usuDesign.PasswordBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Selamat Datang di Aplikasi Pencatatan Laundry");
        panel1.add(jLabel2);
        jLabel2.setBounds(120, 60, 365, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/laundry1111.png"))); // NOI18N
        panel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 70, 70);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel3.setText("Roemah Cemerlang Laundry");
        panel1.add(jLabel3);
        jLabel3.setBounds(120, 30, 293, 29);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/operator2.png"))); // NOI18N
        panel1.add(jLabel7);
        jLabel7.setBounds(50, 110, 128, 128);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Username");
        panel1.add(jLabel4);
        jLabel4.setBounds(200, 140, 61, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        panel1.add(jLabel5);
        jLabel5.setBounds(200, 190, 58, 17);
        panel1.add(jtxtUsername);
        jtxtUsername.setBounds(270, 130, 190, 40);

        jbtnLogin.setForeground(new java.awt.Color(0, 0, 0));
        jbtnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/login.png"))); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.setFocusPainted(false);
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        panel1.add(jbtnLogin);
        jbtnLogin.setBounds(330, 230, 130, 50);

        jtxtPassword.setForeground(new java.awt.Color(0, 0, 0));
        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });
        panel1.add(jtxtPassword);
        jtxtPassword.setBounds(270, 180, 190, 40);

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<Object[]> data = null;
            boolean validasi = false;

            String user = jtxtUsername.getText();
            String pass = jtxtPassword.getText();
            if (user.isEmpty() && pass.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Maaf Username dan Password tidak boleh kosong, Silahkan disisi");
            } else {
                adminCon.cekLogin(user, pass);
                if (adminCon.isStatus()) {
                    new UIDmenuUtama().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Login Gagal, Silahkan Periksa Acount dan Password Anda");
                    reset();
                    jtxtUsername.requestFocus();
                }
            }

        } catch (HeadlessException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private id.aas.apps.mvc.usuDesign.Button jbtnLogin;
    private id.aas.apps.mvc.usuDesign.PasswordBox jtxtPassword;
    private id.aas.apps.mvc.usuDesign.TextBox jtxtUsername;
    private id.aas.apps.mvc.usuDesign.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
