/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.aas.apps.mvc.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aas Suhendar
 */
public class UIDmenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form UIDmenuUtama
     */
    public UIDmenuUtama() {
        initComponents();
        setSize(960, 590);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new id.aas.apps.mvc.usuDesign.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelAlpha1 = new id.aas.apps.mvc.usuDesign.PanelAlpha();
        jbtnPelanggan = new id.aas.apps.mvc.usuDesign.Button();
        jbtnTransaksiKiloan = new id.aas.apps.mvc.usuDesign.Button();
        jbtnViewTransaksi = new id.aas.apps.mvc.usuDesign.Button();
        jbtnHargaSatuan = new id.aas.apps.mvc.usuDesign.Button();
        jbtnTransaksiSatuan = new id.aas.apps.mvc.usuDesign.Button();
        jbtnSettingKiloan = new id.aas.apps.mvc.usuDesign.Button();
        jbtnLogout = new id.aas.apps.mvc.usuDesign.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Selamat Datang di Aplikasi Pencatatan Laundry");
        panel1.add(jLabel2);
        jLabel2.setBounds(90, 10, 365, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/laundry1111.png"))); // NOI18N
        panel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 70, 70);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel3.setText("Roemah Cemerlang Laundry");
        panel1.add(jLabel3);
        jLabel3.setBounds(90, 40, 293, 29);

        panelAlpha1.setBackground(new java.awt.Color(255, 255, 255));
        panelAlpha1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Menu Utama", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        panelAlpha1.setForeground(new java.awt.Color(255, 255, 255));
        panelAlpha1.setLayout(null);

        jbtnPelanggan.setForeground(new java.awt.Color(0, 0, 0));
        jbtnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/guest.png"))); // NOI18N
        jbtnPelanggan.setText("Data Pelanggan");
        jbtnPelanggan.setFocusPainted(false);
        jbtnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPelangganActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnPelanggan);
        jbtnPelanggan.setBounds(610, 20, 270, 120);

        jbtnTransaksiKiloan.setForeground(new java.awt.Color(0, 0, 0));
        jbtnTransaksiKiloan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/aktivitas.png"))); // NOI18N
        jbtnTransaksiKiloan.setText("Transaksi Kiloan");
        jbtnTransaksiKiloan.setFocusPainted(false);
        jbtnTransaksiKiloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTransaksiKiloanActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnTransaksiKiloan);
        jbtnTransaksiKiloan.setBounds(40, 20, 270, 120);

        jbtnViewTransaksi.setForeground(new java.awt.Color(0, 0, 0));
        jbtnViewTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/setting.png"))); // NOI18N
        jbtnViewTransaksi.setText("View Transaksi dan Pengambilan");
        jbtnViewTransaksi.setFocusPainted(false);
        jbtnViewTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewTransaksiActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnViewTransaksi);
        jbtnViewTransaksi.setBounds(260, 160, 410, 120);

        jbtnHargaSatuan.setForeground(new java.awt.Color(0, 0, 0));
        jbtnHargaSatuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/system_preferences.png"))); // NOI18N
        jbtnHargaSatuan.setText("Setting Harga Satuan");
        jbtnHargaSatuan.setFocusPainted(false);
        jbtnHargaSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHargaSatuanActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnHargaSatuan);
        jbtnHargaSatuan.setBounds(470, 300, 290, 120);

        jbtnTransaksiSatuan.setForeground(new java.awt.Color(0, 0, 0));
        jbtnTransaksiSatuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/aktivitas.png"))); // NOI18N
        jbtnTransaksiSatuan.setText("Transaksi Satuan");
        jbtnTransaksiSatuan.setFocusPainted(false);
        jbtnTransaksiSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTransaksiSatuanActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnTransaksiSatuan);
        jbtnTransaksiSatuan.setBounds(330, 20, 270, 120);

        jbtnSettingKiloan.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSettingKiloan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/system_preferences.png"))); // NOI18N
        jbtnSettingKiloan.setText("Setting Harga Kiloan");
        jbtnSettingKiloan.setFocusPainted(false);
        jbtnSettingKiloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSettingKiloanActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnSettingKiloan);
        jbtnSettingKiloan.setBounds(170, 300, 290, 120);

        panel1.add(panelAlpha1);
        panelAlpha1.setBounds(10, 100, 920, 440);

        jbtnLogout.setForeground(new java.awt.Color(0, 0, 0));
        jbtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/exit.png"))); // NOI18N
        jbtnLogout.setText("Logout");
        jbtnLogout.setFocusPainted(false);
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });
        panel1.add(jbtnLogout);
        jbtnLogout.setBounds(780, 10, 150, 60);

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPelangganActionPerformed
        // TODO add your handling code here:
        new UIDPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnPelangganActionPerformed

    private void jbtnViewTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewTransaksiActionPerformed
        // TODO add your handling code here:
        new UIDviewTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnViewTransaksiActionPerformed

    private void jbtnHargaSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHargaSatuanActionPerformed
        // TODO add your handling code here:
        new UIDlaundrySatuan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnHargaSatuanActionPerformed

    private void jbtnTransaksiSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTransaksiSatuanActionPerformed
        // TODO add your handling code here:
        new UIDLaundrySatuanTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnTransaksiSatuanActionPerformed

    private void jbtnSettingKiloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSettingKiloanActionPerformed
        // TODO add your handling code here:
        new UIDlaundryKiloan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnSettingKiloanActionPerformed

    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Terimakasih telah memakai Laundry Apps","Log out",JOptionPane.INFORMATION_MESSAGE);
        System.exit(1);
    }//GEN-LAST:event_jbtnLogoutActionPerformed

    private void jbtnTransaksiKiloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTransaksiKiloanActionPerformed
        // TODO add your handling code here:
        new UIDLaundryKiloanTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnTransaksiKiloanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDmenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDmenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDmenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDmenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDmenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private id.aas.apps.mvc.usuDesign.Button jbtnHargaSatuan;
    private id.aas.apps.mvc.usuDesign.Button jbtnLogout;
    private id.aas.apps.mvc.usuDesign.Button jbtnPelanggan;
    private id.aas.apps.mvc.usuDesign.Button jbtnSettingKiloan;
    private id.aas.apps.mvc.usuDesign.Button jbtnTransaksiKiloan;
    private id.aas.apps.mvc.usuDesign.Button jbtnTransaksiSatuan;
    private id.aas.apps.mvc.usuDesign.Button jbtnViewTransaksi;
    private id.aas.apps.mvc.usuDesign.Panel panel1;
    private id.aas.apps.mvc.usuDesign.PanelAlpha panelAlpha1;
    // End of variables declaration//GEN-END:variables
}
