/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.aas.apps.mvc.view;

import id.aas.apps.mvc.controller.PelangganController;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aas Suhendar
 */
public class UIDPelanggan extends javax.swing.JFrame {

    private PelangganController pController;
    private final DefaultTableModel tableModel;

    /**
     * Creates new form UIDPelanggan
     */
    public UIDPelanggan() {
        initComponents();
        pController = new PelangganController();
        tableModel = new DefaultTableModel();
        jTable.setModel(tableModel);
        this.setSize(855, 480);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        RunApps();
    }

    public PelangganController getpController() {
        return pController;
    }

    public void setpController(PelangganController pController) {
        this.pController = pController;
    }

    public void setTableHeader() {
        Object[] header = pController.getHeaderTablePelanggan();
        for (Object header1 : header) {
            tableModel.addColumn(header1);
        }
    }

    public void setIsiDataPelanggan() {
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();

        ArrayList<Object[]> data = null;
        try {
            data = pController.getAllDataPelanggan();
            for (int i = 0; i < data.size(); i++) {
                tableModel.addRow(data.get(i));
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public void RunApps() {
        try {
            this.setTableHeader();
            this.setIsiDataPelanggan();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void reset() {
        jtxtNama.setText("");
        jtxtTlp.setText("");
        jtxtAreaAlamat.setText("");
        jtxtCari.setText("");
        jbtnSimpanEdit.setText("Simpan");
        jtxtNama.requestFocus();
    }

    public void isiField() {
        int row = jTable.getSelectedRow();
        jtxtNama.setText(jTable.getValueAt(row, 1).toString());
        jtxtTlp.setText(jTable.getValueAt(row, 2).toString());
        jtxtAreaAlamat.setText(jTable.getValueAt(row, 3).toString());
        jbtnSimpanEdit.setText("Edit");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new id.aas.apps.mvc.usuDesign.Panel();
        jLabel1 = new javax.swing.JLabel();
        panelAlpha1 = new id.aas.apps.mvc.usuDesign.PanelAlpha();
        jtxtNama = new id.aas.apps.mvc.usuDesign.TextBox();
        jtxtTlp = new id.aas.apps.mvc.usuDesign.TextBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaAlamat = new id.aas.apps.mvc.usuDesign.TextArea();
        jbtnSimpanEdit = new id.aas.apps.mvc.usuDesign.Button();
        jbtnHapus = new id.aas.apps.mvc.usuDesign.Button();
        jbtnRefresh = new id.aas.apps.mvc.usuDesign.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jtxtCari = new id.aas.apps.mvc.usuDesign.TextBox();
        jbtnMenuUtama = new id.aas.apps.mvc.usuDesign.Button();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/guest.png"))); // NOI18N
        jLabel1.setText("Data Pelanggan Laundry");
        panel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 350, 90);

        panelAlpha1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Form Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));
        panelAlpha1.setForeground(new java.awt.Color(255, 255, 255));
        panelAlpha1.setLayout(null);
        panelAlpha1.add(jtxtNama);
        jtxtNama.setBounds(130, 24, 230, 30);
        panelAlpha1.add(jtxtTlp);
        jtxtTlp.setBounds(130, 64, 230, 30);

        jLabel2.setText("Nama Pelanggan");
        panelAlpha1.add(jLabel2);
        jLabel2.setBounds(10, 30, 110, 14);

        jLabel3.setText("No Telepon");
        panelAlpha1.add(jLabel3);
        jLabel3.setBounds(10, 70, 80, 14);

        jLabel4.setText("Alamat");
        panelAlpha1.add(jLabel4);
        jLabel4.setBounds(10, 100, 80, 14);

        jtxtAreaAlamat.setColumns(20);
        jtxtAreaAlamat.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaAlamat);

        panelAlpha1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 100, 232, 82);

        jbtnSimpanEdit.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSimpanEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/save_all.png"))); // NOI18N
        jbtnSimpanEdit.setText("Simpan");
        jbtnSimpanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSimpanEditActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnSimpanEdit);
        jbtnSimpanEdit.setBounds(120, 190, 120, 40);

        jbtnHapus.setForeground(new java.awt.Color(0, 0, 0));
        jbtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/gnome_edit_delete.png"))); // NOI18N
        jbtnHapus.setText("Hapus");
        jbtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHapusActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnHapus);
        jbtnHapus.setBounds(250, 190, 110, 40);

        jbtnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        jbtnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/arrow_refresh.png"))); // NOI18N
        jbtnRefresh.setText("Refresh");
        jbtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRefreshActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnRefresh);
        jbtnRefresh.setBounds(670, 30, 120, 30);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        panelAlpha1.add(jScrollPane2);
        jScrollPane2.setBounds(410, 70, 370, 140);

        jLabel5.setText("Cari Pelanggan");
        panelAlpha1.add(jLabel5);
        jLabel5.setBounds(410, 40, 100, 14);

        jtxtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCariKeyTyped(evt);
            }
        });
        panelAlpha1.add(jtxtCari);
        jtxtCari.setBounds(500, 30, 160, 30);

        panel1.add(panelAlpha1);
        panelAlpha1.setBounds(10, 120, 820, 260);

        jbtnMenuUtama.setForeground(new java.awt.Color(0, 0, 0));
        jbtnMenuUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/home.png"))); // NOI18N
        jbtnMenuUtama.setText("Menu Utama");
        jbtnMenuUtama.setActionCommand("jbtnMenuUtama");
        jbtnMenuUtama.setFocusPainted(false);
        jbtnMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenuUtamaActionPerformed(evt);
            }
        });
        panel1.add(jbtnMenuUtama);
        jbtnMenuUtama.setBounds(700, 80, 130, 30);

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSimpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSimpanEditActionPerformed
        // TODO add your handling code here:
        try {
            boolean validasi = false;
            String nama = jtxtNama.getText();
            String no_tlp = jtxtTlp.getText();
            String alamat = jtxtAreaAlamat.getText();
            String btnStatus = jbtnSimpanEdit.getText();

            if (nama.isEmpty() || no_tlp.isEmpty() || alamat.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Terdapat Field Kosong, harap mengisi semua field", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (btnStatus.equalsIgnoreCase("Simpan")) {
                    String id = null;
                    validasi = pController.olahDataPelanggan(btnStatus, id, nama, no_tlp, alamat);
                } else {
                    int row = jTable.getSelectedRow();
                    String id = jTable.getValueAt(row, 0).toString();
                    validasi = pController.olahDataPelanggan(btnStatus, id, nama, no_tlp, alamat);
                }

                if (validasi == true) {
                    setIsiDataPelanggan();
                    if (btnStatus.equalsIgnoreCase("Simpan")) {
                        JOptionPane.showMessageDialog(null, "Data Pelanggan Berhasil Disimpan", "Simpan Data Pelanggan", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Pelanggan Berhasil Diedit", "Edit Data Pelanggan", JOptionPane.INFORMATION_MESSAGE);
                    }

                } else {
                    if (btnStatus.equalsIgnoreCase("Simpan")) {
                        JOptionPane.showMessageDialog(null, "Data Pelanggan Gagal Disimpan", "Simpan Data Pelanggan", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Pelanggan Gagal Diedit", "Edit Data Pelanggan", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                reset();
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnSimpanEditActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            isiField();
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jbtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHapusActionPerformed
        // TODO add your handling code here:
        try {
            int row = jTable.getSelectedRow();
            String id_pelanggan = jTable.getValueAt(row, 0).toString();
            System.out.println(id_pelanggan);

            boolean validasi = pController.hapusDataPelanggan(id_pelanggan);
            if (validasi == true) {
                setIsiDataPelanggan();
                JOptionPane.showMessageDialog(null, "Data Pelanggan Berhasil Dihapus", "Hapus Data Pelanggan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Data Pelanggan Gagal Dihapus", "Hapus Data Pelanggan", JOptionPane.INFORMATION_MESSAGE);
            }
            reset();

        } catch (HeadlessException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jbtnHapusActionPerformed

    private void jbtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRefreshActionPerformed
        // TODO add your handling code here:
        setIsiDataPelanggan();
        reset();
    }//GEN-LAST:event_jbtnRefreshActionPerformed

    private void jbtnMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenuUtamaActionPerformed
        // TODO add your handling code here:
        new UIDmenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnMenuUtamaActionPerformed

    private void jtxtCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCariKeyTyped
        // TODO add your handling code here:
        try {
            tableModel.getDataVector().removeAllElements();
            tableModel.fireTableDataChanged();
            ArrayList<Object[]> data = null;
            String cari = jtxtCari.getText();
            data=pController.cariDataPelangggan(cari);
            for (int i = 0; i < data.size(); i++) {
                tableModel.addRow(data.get(i));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jtxtCariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private id.aas.apps.mvc.usuDesign.Button jbtnHapus;
    private id.aas.apps.mvc.usuDesign.Button jbtnMenuUtama;
    private id.aas.apps.mvc.usuDesign.Button jbtnRefresh;
    private id.aas.apps.mvc.usuDesign.Button jbtnSimpanEdit;
    private id.aas.apps.mvc.usuDesign.TextArea jtxtAreaAlamat;
    private id.aas.apps.mvc.usuDesign.TextBox jtxtCari;
    private id.aas.apps.mvc.usuDesign.TextBox jtxtNama;
    private id.aas.apps.mvc.usuDesign.TextBox jtxtTlp;
    private id.aas.apps.mvc.usuDesign.Panel panel1;
    private id.aas.apps.mvc.usuDesign.PanelAlpha panelAlpha1;
    // End of variables declaration//GEN-END:variables
}
