/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.aas.apps.mvc.view;

import id.aas.apps.mvc.controller.viewTransaksiController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aas Suhendar
 */
public class UIDviewTransaksi extends javax.swing.JFrame {

    private viewTransaksiController viewControler;
    private DefaultTableModel tableModel;
    String sortir;
    private JComboBox jComboAmbil;
    private JComboBox jComboBayar;

    /**
     * Creates new form UIDviewTransaksi
     */
    public UIDviewTransaksi() {
        initComponents();
        viewControler = new viewTransaksiController();
        tableModel = new DefaultTableModel();
        jTable1.setModel(tableModel);
        jComboAmbil = new JComboBox(new String[]{"Belum Di Ambil", "Sudah Diambil"});
        jComboBayar = new JComboBox(new String[]{"Lunas", "Cash Bon"});
        this.setSize(1150, 600);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        runApps();
    }

    public viewTransaksiController getViewControler() {
        return viewControler;
    }

    public void setViewControler(viewTransaksiController viewControler) {
        this.viewControler = viewControler;
    }

    public void setTableHeader() {
        Object[] tableHeader = viewControler.getHeaderTableTransaksi();
        for (Object tableHeader1 : tableHeader) {
            tableModel.addColumn(tableHeader1);
        }
    }

    public void setIsiDataTransaksi() {
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();

        ArrayList<Object[]> data = null;
        try {
            data = viewControler.getAllDataTransaksi();
            for (int i = 0; i < data.size(); i++) {
                tableModel.addRow(data.get(i));
            }
            jTable1.getColumnModel().getColumn(11).setCellEditor(new DefaultCellEditor(jComboAmbil));
            jTable1.getColumnModel().getColumn(12).setCellEditor(new DefaultCellEditor(jComboBayar));
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public void runApps() {
        try {
            this.setTableHeader();
            this.setIsiDataTransaksi();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void reset() {
        try {
            jtxtCari.setText("");
            jComboCari.setSelectedIndex(0);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new id.aas.apps.mvc.usuDesign.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelAlpha1 = new id.aas.apps.mvc.usuDesign.PanelAlpha();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboCari = new javax.swing.JComboBox();
        jtxtCari = new id.aas.apps.mvc.usuDesign.TextBox();
        button1 = new id.aas.apps.mvc.usuDesign.Button();
        button2 = new id.aas.apps.mvc.usuDesign.Button();
        jbtnRefresh = new id.aas.apps.mvc.usuDesign.Button();
        jbtnMenuUtama = new id.aas.apps.mvc.usuDesign.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/aktivitas.png"))); // NOI18N
        jLabel1.setText("Transaksi Laundry");
        panel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 320, 108);

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel6.setText("Aplikasi Pencatatan Laundry");
        panel1.add(jLabel6);
        jLabel6.setBounds(820, 20, 221, 22);

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel7.setText("Roemah Cemerlang Laundry");
        panel1.add(jLabel7);
        jLabel7.setBounds(750, 50, 293, 29);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/laundry1111.png"))); // NOI18N
        panel1.add(jLabel8);
        jLabel8.setBounds(1050, 10, 70, 70);

        panelAlpha1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "View Transaksi & Pengambilan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        panelAlpha1.setForeground(new java.awt.Color(255, 255, 255));
        panelAlpha1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelAlpha1.add(jScrollPane1);
        jScrollPane1.setBounds(13, 83, 1090, 226);

        jLabel2.setText("Cari");
        panelAlpha1.add(jLabel2);
        jLabel2.setBounds(19, 50, 30, 14);

        jComboCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Kode Transaksi", "Nama Pelanggan", "Jenis Layanan" }));
        jComboCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCariActionPerformed(evt);
            }
        });
        panelAlpha1.add(jComboCari);
        jComboCari.setBounds(60, 40, 105, 30);

        jtxtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCariKeyTyped(evt);
            }
        });
        panelAlpha1.add(jtxtCari);
        jtxtCari.setBounds(170, 40, 250, 30);

        button1.setForeground(new java.awt.Color(0, 0, 0));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/gnome_system_software_update.png"))); // NOI18N
        button1.setText("Update");
        button1.setActionCommand("jbtnUpdate");
        button1.setFocusPainted(false);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelAlpha1.add(button1);
        button1.setBounds(970, 320, 130, 40);

        button2.setForeground(new java.awt.Color(0, 0, 0));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/lapor.png"))); // NOI18N
        button2.setText("Grafik Analisis");
        button2.setActionCommand("jbtnGrafikPengguna");
        button2.setFocusPainted(false);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelAlpha1.add(button2);
        button2.setBounds(20, 320, 230, 53);

        jbtnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        jbtnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/arrow_refresh.png"))); // NOI18N
        jbtnRefresh.setText("Refresh");
        jbtnRefresh.setFocusPainted(false);
        jbtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRefreshActionPerformed(evt);
            }
        });
        panelAlpha1.add(jbtnRefresh);
        jbtnRefresh.setBounds(430, 40, 130, 30);

        panel1.add(panelAlpha1);
        panelAlpha1.setBounds(10, 160, 1120, 380);

        jbtnMenuUtama.setForeground(new java.awt.Color(0, 0, 0));
        jbtnMenuUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/aas/apps/mvc/images/home.png"))); // NOI18N
        jbtnMenuUtama.setText("Menu Utama");
        jbtnMenuUtama.setActionCommand("jbtnMenuUtama");
        jbtnMenuUtama.setFocusPainted(false);
        jbtnMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenuUtamaActionPerformed(evt);
            }
        });
        panel1.add(jbtnMenuUtama);
        jbtnMenuUtama.setBounds(1000, 120, 130, 30);

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCariActionPerformed
        // TODO add your handling code here:
        try {
            int opsi = jComboCari.getSelectedIndex();
            if (opsi == 1) {
                sortir = "TRANSAKSI.KD_TRANSAKSI";
                System.out.println(sortir);
            } else if (opsi == 2) {
                sortir = "PELANGGAN.NAMA";
                System.out.println(sortir);
            } else {
                sortir = "LAUNDRY.JENIS_LAYANAN";
                System.out.println(sortir);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboCariActionPerformed

    private void jtxtCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCariKeyTyped
        // TODO add your handling code here:
        try {
            tableModel.getDataVector().removeAllElements();
            tableModel.fireTableDataChanged();
            String nama = jtxtCari.getText();
            ArrayList<Object[]> data=null;
            data=viewControler.searchDataTransaksi(sortir, nama);
            for (int i = 0; i < data.size(); i++) {
                tableModel.addRow(data.get(i));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jtxtCariKeyTyped

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        try {
            new frameChart().setVisible(true);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void jbtnMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenuUtamaActionPerformed
        // TODO add your handling code here:
        new UIDmenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnMenuUtamaActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        try {
            boolean validasi = false;
            int row = jTable1.getSelectedRow();
            if (row < 0) {
                return;
            }
            String kd_transaksi = jTable1.getValueAt(row, 0).toString();
            String kd_laundry = jTable1.getValueAt(row, 1).toString();
            String keteranganT = jTable1.getValueAt(row, 12).toString();
            String keteranganL = jTable1.getValueAt(row, 11).toString();
            validasi = viewControler.updatePengambilan(kd_laundry, keteranganL, kd_transaksi, keteranganT);
            if (validasi == true) {
                JOptionPane.showMessageDialog(null, "Pengembilan Laundry Berhasil, Data di Update", "Pengambilan Laundry", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Pengembilan Laundry Gagal, Data di Tidak Update", "Pengambilan Laundry", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void jbtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRefreshActionPerformed
        // TODO add your handling code here:
        reset();
        setIsiDataTransaksi();
    }//GEN-LAST:event_jbtnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDviewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDviewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDviewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDviewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDviewTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private id.aas.apps.mvc.usuDesign.Button button1;
    private id.aas.apps.mvc.usuDesign.Button button2;
    private javax.swing.JComboBox jComboCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private id.aas.apps.mvc.usuDesign.Button jbtnMenuUtama;
    private id.aas.apps.mvc.usuDesign.Button jbtnRefresh;
    private id.aas.apps.mvc.usuDesign.TextBox jtxtCari;
    private id.aas.apps.mvc.usuDesign.Panel panel1;
    private id.aas.apps.mvc.usuDesign.PanelAlpha panelAlpha1;
    // End of variables declaration//GEN-END:variables
}
